### PR TITLE
fixes for assembly of Z-axis (threaded rods)

### PR DESCRIPTION
**Pull request by magillus**
Fix for threaded rod not being parallel to smooth rods on z-axis.
Added assembly for z axis and updated main assembly.

### CODE REVIEW

**Comment by magillus** [comment]
z-axis fixed
Fixed z-axis after printed elements.
There were 2 things off - I was using older printed base for motor (which was fixed already in first pull request but I used older version of it), second thing was 1mm off in top bearing holder element. which was fixed in this pull request.

**Comment by magillus** [comment]
video with working z axis - https://plus.google.com/+MateuszPerlak/posts/3q2wyorSg6w

**Comment by smartfriendz** [comment]
thx for the fix. but... the main option ( wich i work with ) is broken . rod is not inline with ztop.
I think it was a mistake from the first merge.
I would prefer to come back to the version before all merges and do the merge again in a new brach (dev) ? It would be more serious and more practical for production .
When all is ok, we can merge the two branches dev and production.

**Comment by magillus** [comment]
I will review and update.
You can disable or remove threaded rod option, I will post my designs in youmagine as upgrade,  it doesn't need to be at your sources.

**Comment by magillus** [comment]
Updated and fixed assembly option for belt.

**Pull request closed without merging**
