### PR TITLE
Z.axis threaded.rods

### PR DESCRIPTION
**Pull request by magillus**
Not 3d printed.

possible improvements:
- current implementation takes too much space on bottom - added height of the motor.
- all assembly view doesn't change motor location and mounting for Z threaded rods option

please review and no need to merge - I will work on those 2 issues.

For bigger platform I plan to use 2 Z threaded rods on sides (similar to original prusa i3)

### CODE REVIEW

**Comment by smartfriendz** [comment]
it works very well. thank you ! tell me when you're happy. I will merge it. It's very good option . I will try to print and test also.

**Comment by smartfriendz** [comment]
about the belt length. I use a 122 cm length belt for each X Y . I have 2 cm left behind the head after attachment.
I didn't read the code for now, i will investigate where we can adjust ?

**Comment by magillus** [comment]
I think I can swap top and bottom z-axis mounts and that will not change bed lowest position.
Thanks to bearing and nut on rod at the bearing location all weight will be on that bearing not on motor's coupler.
Only thing will be that I can't use that approach on sides where there are Y rods. My printer size will be 400x340x350 so it will need 2 z-axis-es, probably can sacrifice 50mm of Z.

I will update pull request with that on general assembly and it will be ready for merge.

**Comment by magillus** [comment]
Updated:
Added assembly with 2 axis rods on sides and single.

Please merge if all ok.

**Comment by smartfriendz** [comment]
all seems great :) thank you . it's a good option.

**Pull request merged**
